/* TagVFS configuration snapshot utility executable.
 * AGPL-3.0 license
 * Initial rev Misha Turnbull 2023-11-12
 *
 * Impelements the configuration snapshot utility.
 */

#include "cfgsnapshot_exe.h"

/* (not a doc comment!)
 *
 * These variables are compiled in from _config_h.o and _version_autogen.o
 * files that don't exist.  They will not exist until compile time.  You won't
 * find them anywhere in the sourcecode.
 *
 * If you're here because something broke, please also pay careful attention to
 * the CMakeLists.txt responsible for building this executable.  The overall
 * process is something like this:
 *
 * 1. User presses "please build" button
 * 2. CMake makes its way over to this executable
 * 3. Two custom targets have been declared as dependencies for this binary:
 *    ``config_h`` and ``_version_autogen`` (no ``.o`` on these ones!)
 * 4. CMake uses the linker to build these objects
 * 5. The ``.o`` files generated by the linker are compiled alongside *this*
 *    file as sourcecode
 * 6. Those ``.o`` files declare the six symbols below
 *
 * .. seealso::
 *
 *    The laundry list of StackOverflow questions that led this into existence:
 *
 *    * https://stackoverflow.com/q/4158900
 *    * https://stackoverflow.com/q/52830564
 *    * https://stackoverflow.com/q/14776463
 *    * https://stackoverflow.com/q/38609303
 *    * https://stackoverflow.com/q/11813271
 *    * https://stackoverflow.com/q/65407610
 *    * https://stackoverflow.com/q/19169039
 *
 *    The :file:`CMakeLists.txt` responsible for this executable
 *
 */
extern char _binary_config_h_start[];
extern char _binary_config_h_end[];
extern size_t _binary_config_h_size;
extern char _binary_version_autogen_h_start[];
extern char _binary_version_autogen_h_end[];
extern size_t _binary_version_autogen_h_size;

static char doc[] = "Dump information about TagVFS compilation flags.";

static struct argp argp = {0, 0, 0, doc, 0, 0, 0};

int main(int argc, char **argv) {
    // no arguments taken here!
    argp_parse(&argp, argc, argv, 0, 0, 0);

    for (char *p = _binary_config_h_start;
            p != _binary_config_h_end;
            p++) {
        putchar(*p);
    }
    for (char *p = _binary_version_autogen_h_start;
            p != _binary_version_autogen_h_end;
            p++) {
        putchar(*p);
    }

    return 0;
}

